##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://aimarinello.github.io
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /La_voz_CSV
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-csv

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Colección Patrimonial La Voz
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Periodico chileno del siglo XX
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "La revista La Voz, que surgió en 1953 como medio del Arzobispado de Santiago y se transformó en semanario hasta 1964, está ahora disponible en la Biblioteca de Humanidades gracias a la donación de Abraham Santibáñez. La colección incluye cuatro tomos empastados y 34 ejemplares sueltos, realizados por destacados profesionales. Esta colección digital ofrece al público una valiosa fuente de información sobre hechos históricos y sociales, destacando artículos de autores reconocidos y preservando la historia."

# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: idaho; history; inland northwest
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Adolfo Marinello

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the CSV file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: metadatos_la_voz
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
# page_gen:
#   - data: 'demo-metadata'
#     template: 'item'
#     name: 'objectid'
#     dir: 'items'
#     extension: 'html' 
#     filter: 'objectid'  

##########
# Site/Organization Branding 
#   Enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#   To remove the branding, comment out these values, or delete them. 
#
organization-name: "Sistema de Bibliotecas UC"
organization-link: https://bibliotecas.uc.cl/
organization-logo-banner: https://bibliotecas.uc.cl/templates/plantillaucresponsivaj3/images/logo-uc.svg
organization-logo-nav: https://bibliotecas.uc.cl/templates/plantillaucresponsivaj3/images/logo-uc.svg

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, rakelib/, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md]
# compress CSS output
sass:
  style: compressed
